package com.APIHotels.pages.generic;

import org.openqa.selenium.support.events.EventFiringWebDriver;

import com.APIHotels.pages.ACES3.Page_AccountConfirmation_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_AccountManagement_Aces3Client;
import com.APIHotels.pages.ACES3.Page_AccountManagement_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_AccountingFinancialReport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_Accounting_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_Accounting_Aces3Client;
import com.APIHotels.pages.ACES3.Page_PendingActionQueue_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_AccurualSnapshot_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_Admin_Aces3Client;
import com.APIHotels.pages.ACES3.Page_AirlinesReport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_ChallengeInvoice_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_Configuration_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_ConsolidatedEInvoiceReport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_CreateAllowanceInvoice_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_CreateInvoice_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_CreateRole_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_CreateUser_Aces3Aces;
import com.APIHotels.pages.ACES3.Page_CreateUser_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_CreateViewAllowanceSIS_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_CrewIDIssuesReport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_EDriveDashboard_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_EditUserAccount_Aces3Aces;
import com.APIHotels.pages.ACES3.Page_EditUserAccount_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_EnterOnlineSignInSheets_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_FindAllowanceInvoice_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_FindInvoice_Aces3Client;
import com.APIHotels.pages.ACES3.Page_Home_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_Home_Aces3Client;
import com.APIHotels.pages.ACES3.Page_Home_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_InvoiceComplianceReport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_InvoiceDashboard_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_InvoiceStatusReport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_Login_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_Login_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_ManageEDrive_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_ManageRoles_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_ManageUsers_Aces3Aces;
import com.APIHotels.pages.ACES3.Page_ManageUsers_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_ManualInvoice_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_MasterOpsReport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_NewInvoices_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_NoShowreport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_RecoverableTaxReport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_Reports_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_Reservations_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_ReviewedInvoices_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_SearchAdhocAllowanceRequest_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_SignInSheets_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_SignInSheets_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_SupplierSchedules_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_TaxExemptionReport_ACES3ACES;
import com.APIHotels.pages.ACES3.Page_TaxInvoice_Aces3Client;
import com.APIHotels.pages.ACES3.Page_TaxInvoice_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_UploadInvoice_Aces3Supplier;
import com.APIHotels.pages.ACES3.Page_ViewAllowanceForecasts_Aces3Supplier;
import com.APIHotels.pages.ACESII.Page_AddHotelReservation;
import com.APIHotels.pages.ACESII.Page_AddHotelReservationInformation;
import com.APIHotels.pages.ACESII.Page_AddNewAirlineSupplier;
import com.APIHotels.pages.ACESII.Page_AddNewCommonSupplier;
import com.APIHotels.pages.ACESII.Page_AgentReport;
import com.APIHotels.pages.ACESII.Page_AirlineGTSupplier;
import com.APIHotels.pages.ACESII.Page_AirlineHotelSupplier;
import com.APIHotels.pages.ACESII.Page_AirlineReport;
import com.APIHotels.pages.ACESII.Page_AirportToAirportTransitTimes;
import com.APIHotels.pages.ACESII.Page_ApproveManualInvoice;
import com.APIHotels.pages.ACESII.Page_Assignments;
import com.APIHotels.pages.ACESII.Page_BulkAssign;
import com.APIHotels.pages.ACESII.Page_CancelReservation;
import com.APIHotels.pages.ACESII.Page_CommonGTGeneralInfo;
import com.APIHotels.pages.ACESII.Page_CommonHotelGeneralInfo;
import com.APIHotels.pages.ACESII.Page_Configuration;
import com.APIHotels.pages.ACESII.Page_CreateConsolidatedInvoices;
import com.APIHotels.pages.ACESII.Page_CreateConsolidatedReconcileInvoice;
import com.APIHotels.pages.ACESII.Page_CreateManualInvoice;
import com.APIHotels.pages.ACESII.Page_CreateProfarmaInvoices;
import com.APIHotels.pages.ACESII.Page_CreateSchedules;
import com.APIHotels.pages.ACESII.Page_CreditCardReport;
import com.APIHotels.pages.ACESII.Page_DashBoard;
import com.APIHotels.pages.ACESII.Page_ErrorsWarnings;
import com.APIHotels.pages.ACESII.Page_ExportPairings;
import com.APIHotels.pages.ACESII.Page_FaxStatus;
import com.APIHotels.pages.ACESII.Page_FindCommonSupplier;
import com.APIHotels.pages.ACESII.Page_FindExistingAirlineSupplier;
import com.APIHotels.pages.ACESII.Page_FindGTSchedules;
import com.APIHotels.pages.ACESII.Page_FindInvoice;
import com.APIHotels.pages.ACESII.Page_FindReconcileInvoice;
import com.APIHotels.pages.ACESII.Page_FindReservation;
import com.APIHotels.pages.ACESII.Page_FindSheet;
import com.APIHotels.pages.ACESII.Page_FindTrip;
import com.APIHotels.pages.ACESII.Page_GTEInvoiceConfiguration;
import com.APIHotels.pages.ACESII.Page_GTInvoicing_CreateManaulInvoice;
import com.APIHotels.pages.ACESII.Page_GTInvoicing_EdriveGTDashboard;
import com.APIHotels.pages.ACESII.Page_GTSchedules;
import com.APIHotels.pages.ACESII.Page_GateTimes;
import com.APIHotels.pages.ACESII.Page_GenerateCrewSignInSheet;
import com.APIHotels.pages.ACESII.Page_GtEInvoicing_CreateInvoice;
import com.APIHotels.pages.ACESII.Page_GtEInvoicing_FindInvoices;
import com.APIHotels.pages.ACESII.Page_Home;
import com.APIHotels.pages.ACESII.Page_HotelAllowanceConfiguration;
import com.APIHotels.pages.ACESII.Page_HotelExport;
import com.APIHotels.pages.ACESII.Page_HotelSchedules;
import com.APIHotels.pages.ACESII.Page_HotelSupplier_ContractDetails;
import com.APIHotels.pages.ACESII.Page_IgnoreReservation;
import com.APIHotels.pages.ACESII.Page_LockSchedules;
import com.APIHotels.pages.ACESII.Page_Login_ACESII;
import com.APIHotels.pages.ACESII.Page_ManageGroundTransportSchedule;
import com.APIHotels.pages.ACESII.Page_ManageGroups;
import com.APIHotels.pages.ACESII.Page_ManageOpenInvoice;
import com.APIHotels.pages.ACESII.Page_ManageTenantFeatures;
import com.APIHotels.pages.ACESII.Page_ManageUsers;
import com.APIHotels.pages.ACESII.Page_ManageVenues;
import com.APIHotels.pages.ACESII.Page_Migrate;
import com.APIHotels.pages.ACESII.Page_MultiNightGrouping;
import com.APIHotels.pages.ACESII.Page_PendingConfirmations;
import com.APIHotels.pages.ACESII.Page_ReadyToExport;
import com.APIHotels.pages.ACESII.Page_Reports;
import com.APIHotels.pages.ACESII.Page_ScheduleNotes;
import com.APIHotels.pages.ACESII.Page_SignInReport;
import com.APIHotels.pages.ACESII.Page_SortSuppliers;
import com.APIHotels.pages.ACESII.Page_TripAssignmentConfirmation;
import com.APIHotels.pages.ACESII.Page_TripTrackingReport;
import com.APIHotels.pages.ACESII.Page_ViewConsolidatedInvoice;
import com.APIHotels.pages.ACESII.Page_ViewConsolidatedReconcileInvoice;
import com.APIHotels.pages.ACESII.Page_ViewSchedules;
import com.APIHotels.pages.airlines.AccountingReportsPage;
import com.APIHotels.pages.airlines.AcesDirectFindReservationPage;
import com.APIHotels.pages.airlines.AcesDirectRequestLimoPage;
import com.APIHotels.pages.airlines.AcesDirectRequestReservationPage;
import com.APIHotels.pages.airlines.ActionGTApprovedInvoicePage;
import com.APIHotels.pages.airlines.ActionGTInvoicePage;
import com.APIHotels.pages.airlines.ActionStatusPage;
import com.APIHotels.pages.airlines.AirNelsonReportPage;
import com.APIHotels.pages.airlines.AirlinesLoginPage;
import com.APIHotels.pages.airlines.ApprovedInvoicesPage;
import com.APIHotels.pages.airlines.AuditHistoryPage;
import com.APIHotels.pages.airlines.CATTSApprovalPage;
import com.APIHotels.pages.airlines.CATTSReportPage;
import com.APIHotels.pages.airlines.ConfigureSupplierFeaturesPage;
import com.APIHotels.pages.airlines.ConsolidateRoomSummaryReportPage;
import com.APIHotels.pages.airlines.CreateAdhocAllowancePage;
import com.APIHotels.pages.airlines.CreateUserPage;
import com.APIHotels.pages.airlines.CrewIDIssueReportPage;
import com.APIHotels.pages.airlines.DEAReportPage;
import com.APIHotels.pages.airlines.DeadHeadsPage;
import com.APIHotels.pages.airlines.EditProfilePage;
import com.APIHotels.pages.airlines.ExportAssignedPairingsPage;
import com.APIHotels.pages.airlines.ExportHotelsPage;
import com.APIHotels.pages.airlines.ExportPairingsPage;
import com.APIHotels.pages.airlines.FindGTInvoicePage;
import com.APIHotels.pages.airlines.FindInvoicesPage;
import com.APIHotels.pages.airlines.FindOrEditRoomBlockRequestsPage;
import com.APIHotels.pages.airlines.FindPairingsPage;
import com.APIHotels.pages.airlines.FindReservationBTPage;
import com.APIHotels.pages.airlines.FindReservationsPage;
import com.APIHotels.pages.airlines.FindSheetPage;
import com.APIHotels.pages.airlines.FindUserPage;
import com.APIHotels.pages.airlines.GLCodeReportPage;
import com.APIHotels.pages.airlines.GTConsolidatedInvoicePage;
import com.APIHotels.pages.airlines.GTOPSSchedulePage;
import com.APIHotels.pages.airlines.GTOracleReportPage;
import com.APIHotels.pages.airlines.GTPaymentFileReportsPage;
import com.APIHotels.pages.airlines.GTUsageGroundTransportationPage;
import com.APIHotels.pages.airlines.GTUsagePage;
import com.APIHotels.pages.airlines.GTUsageReportPage;
import com.APIHotels.pages.airlines.GenerateSheetPage;
import com.APIHotels.pages.airlines.HotelInfoPage;
import com.APIHotels.pages.airlines.ManageDateConfigurationPage;
import com.APIHotels.pages.airlines.ManageGroupsPage;
import com.APIHotels.pages.airlines.NoShowReportPage;
import com.APIHotels.pages.airlines.Page_GroundTransportation;
import com.APIHotels.pages.airlines.PaymentExtractReportPage;
import com.APIHotels.pages.airlines.PlanningReportsPage;
import com.APIHotels.pages.airlines.ReconcilledInvoicesPage;
import com.APIHotels.pages.airlines.RequestConferenceRoomPage;
import com.APIHotels.pages.airlines.RequestLimoPage;
import com.APIHotels.pages.airlines.RequestReservationPage;
import com.APIHotels.pages.airlines.RequestRoomBlockPage;
import com.APIHotels.pages.airlines.ReservationPage;
import com.APIHotels.pages.airlines.RoomUsageExtractPage;
import com.APIHotels.pages.airlines.RoomUsagePage;
import com.APIHotels.pages.airlines.SearchAdhocAllowancePage;
import com.APIHotels.pages.airlines.SupplierInvoicesPage;
import com.APIHotels.pages.airlines.SupplierSchedulesPage;
import com.APIHotels.pages.airlines.SystemAdminPage;
import com.APIHotels.pages.airlines.TaxExemptionReportPage;
import com.APIHotels.pages.airlines.TaxGLCodeReportPage;
import com.APIHotels.pages.airlines.UploadPairingsPage;
import com.APIHotels.pages.airlines.UploadRoamingListPage;
import com.APIHotels.pages.airlines.VendorMismatchPage;
import com.APIHotels.pages.airlines.ViewAllowanceInvoicePage;
import com.APIHotels.pages.airlines.ViewAllowanceTransactionsPage;
import com.APIHotels.pages.airlines.ViewApprovedAllowanceInvoicePage;
import com.APIHotels.pages.airlines.ViewForecastsPage;
import com.APIHotels.pages.airlines.ViewResourceStatusPage;
import com.APIHotels.pages.airlines.ViewSubmittedAllowanceInvoicesPage;
import com.APIHotels.pages.navigationalLinks.ACESII.AccountingMenu;
import com.APIHotels.pages.navigationalLinks.ACESII.AdminMenu;
import com.APIHotels.pages.navigationalLinks.ACESII.OpsDeskMenu;
import com.APIHotels.pages.navigationalLinks.ACESII.PlanningMenu;
import com.APIHotels.pages.navigationalLinks.ACESII.ReportsMenu;
import com.APIHotels.pages.navigationalLinks.ACESII.SchedulesMenu;
import com.APIHotels.pages.navigationalLinks.ACESII.SupplierProfileMenu;
import com.APIHotels.pages.navigationalLinks.Airlines.AccountingTab;
import com.APIHotels.pages.navigationalLinks.Airlines.AdminTab;
import com.APIHotels.pages.navigationalLinks.Airlines.ChangeTenantLink;
import com.APIHotels.pages.navigationalLinks.Airlines.MyAccountTab;
import com.APIHotels.pages.navigationalLinks.Airlines.OperationsTab;
import com.APIHotels.pages.navigationalLinks.Airlines.PlanningTab;
import com.APIHotels.pages.navigationalLinks.Airlines.ReportsTab;

public class PgWrapper {

	public Page_Login_ACESII pageLoginACESII;
	public Page_Home pageHome;
	public SupplierProfileMenu supplierProfileMenu;
	public Page_AddNewAirlineSupplier pageAddNewAirlineSupplier;
	public Page_AirlineHotelSupplier pageAirlineHotelSupplier;
	public Page_AirlineGTSupplier pageAirlineGTSupplier;
	public Page_HotelSupplier_ContractDetails pageHotelSupplierContractDetails;
	public Page_FindExistingAirlineSupplier pageFindExistingAirlineSupplier;
	public Page_AddNewCommonSupplier pageAddNewCommonSupplier;
	public Page_FindCommonSupplier pageFindCommonSupplier;
	public Page_CommonHotelGeneralInfo pageCommonHotelGeneralInfo;
	public Page_CommonGTGeneralInfo pageCommonGTGeneralInfo;
	public Page_SortSuppliers pageSortSuppliers;
	public Page_AirportToAirportTransitTimes pageAirportToAirportTransitTimes;
	public Page_GateTimes pageGateTimes;
	public Page_ManageVenues pageManageVenues;

	public PlanningMenu planningMenu;
	public Page_BulkAssign bulkAssignPage;
	public Page_ErrorsWarnings errorsWarningsPage;
	public Page_Assignments assignmentsPage;
	public Page_ExportPairings exportPairingsPage;
	public Page_Migrate migratePage;
	public Page_Configuration configurationPage;

	public SchedulesMenu schedulesMenu;
	public Page_CreateSchedules createSchedulesPage;
	public Page_ViewSchedules viewSchedulesPage;
	public Page_ScheduleNotes scheduleNotesPage;
	public Page_LockSchedules lockSchedulesPage;
	public Page_ReadyToExport readyToExportPage;

	public OpsDeskMenu opsDeskMenu;
	public Page_DashBoard pageDashBoard;
	public Page_FindTrip pageFindTrip;
	public Page_PendingConfirmations pagePendingConfirmations;
	public Page_HotelSchedules pageHotelSchedules;
	public Page_GTSchedules pageGTSchedules;
	public Page_FindGTSchedules pageFindGTSchedules;
	public Page_FindReservation pageFindReservation;
	public Page_AddHotelReservation pageAddHotelReservation;
	public Page_AddHotelReservationInformation pageAddHotelReservationInformation;
	public Page_GenerateCrewSignInSheet pageGenerateCrewSignInSheet;
	public Page_FindSheet pageFindSheet;
	public Page_IgnoreReservation pageIgnoreReservation;
	public Page_CancelReservation pageCancelReservation;
	public Page_TripAssignmentConfirmation pageTripAssignmentConfirmation;

	public AccountingMenu accountingMenu;
	public Page_SignInReport pageSignInReport;
	public Page_FindInvoice pageFindInvoice;
	public Page_ManageOpenInvoice pageManageOpenInvoice;
	public Page_CreateManualInvoice pageCreateManualInvoice;
	public Page_ApproveManualInvoice pageApproveManualInvoice;
	public Page_CreateProfarmaInvoices pageCreateProfarmaInvoices;
	public Page_CreateConsolidatedInvoices pageCreateConsolidatedInvoices;
	public Page_ViewConsolidatedInvoice pageViewConsolidatedInvoices;
	public Page_FindReconcileInvoice pageFindReconcileInvoie;
	public Page_CreateConsolidatedReconcileInvoice pageCreateConsolidatedReconcileInvoice;
	public Page_ViewConsolidatedReconcileInvoice pageViewConsolidatedReconcileInvoice;
	public Page_CreditCardReport pageCreditCardReport;
	public Page_GtEInvoicing_CreateInvoice pageGTInvoicingCreateInvoice;
	public Page_GtEInvoicing_FindInvoices pageGTInvoicingFindInvoice;
	public Page_GTInvoicing_EdriveGTDashboard pageGTInvoicingEdriveDashboard;

	public AdminMenu adminMenu;
	public Page_ManageUsers pageManageUsers;
	public Page_ManageGroups pageManageGroups;
	public Page_ManageTenantFeatures pageManageTenantFeatures;
	public Page_FaxStatus pagefaxStatus;
	public Page_GTEInvoiceConfiguration pageGtEInvoiceConfiguration;
	public Page_ManageGroundTransportSchedule pageManageGroundTransportSchedule;
	public Page_HotelAllowanceConfiguration pageHotelAllowanceConfiguration;
	public Page_MultiNightGrouping pageMultiNightGrouping;

	public ReportsMenu reportsMenu;
	public Page_Reports pageReports;
	public Page_HotelExport pageHotelExport;
	public Page_AgentReport pageAgentReport;
	public Page_AirlineReport pageAirlineReport;
	public Page_TripTrackingReport pageTripTrackingReport;

	public AirlinesLoginPage airlinesLoginPage;

	public PlanningTab planningTab;
	public ExportAssignedPairingsPage exportAssignedPairingsPage;
	public ExportHotelsPage exportHotelsPage;
	public ExportPairingsPage exportPairingPage;
	public SupplierSchedulesPage supplierSchedulesPage;
	public UploadPairingsPage uploadPairingsPage;
	public UploadRoamingListPage uploadRoamingListPage;

	public OperationsTab operationsTab;
	public FindPairingsPage findPairingsPage;
	public AcesDirectFindReservationPage acesDirectFindReservationPage;
	public AcesDirectRequestLimoPage acesDirectRequestLimoPage;
	public AcesDirectRequestReservationPage acesDirectRequestReservationPage;
	public ActionStatusPage actionStatusPage;
	public FindReservationBTPage findReservationBTPage;
	public FindReservationsPage findReservationsPage;
	public FindSheetPage findSheetPage;
	public FindOrEditRoomBlockRequestsPage findOrEditRoomBlockRequestsPage;
	public GenerateSheetPage generateSheetPage;
	public ViewForecastsPage viewForecastsPage;
	public HotelInfoPage hotelInfoPage;
	public DeadHeadsPage deadHeadsPage;
	public DEAReportPage deaReportPage;
	public CreateAdhocAllowancePage createAdhocAllowancePage;
	public PaymentExtractReportPage paymentExtractReportPage;
	public RequestConferenceRoomPage requestConferenceRoomPage;
	public RequestLimoPage requestLimoPage;
	public RequestReservationPage requestReservationPage;
	public RequestRoomBlockPage requestRoomBlockPage;
	public ReservationPage reservationPage;
	public RoomUsagePage roomUsagePage;
	public SearchAdhocAllowancePage searchAdhocAllowancePage;
	public ViewApprovedAllowanceInvoicePage viewApprovedAllowanceInvoicePage;
	public ViewAllowanceInvoicePage viewAllowanceInvoicePage;
	public ViewAllowanceTransactionsPage viewAllowanceTransactionsPage;
	public VendorMismatchPage vendorMismatchPage;
	public ConfigureSupplierFeaturesPage configureSupplierFeaturesPage;
	public AirNelsonReportPage airNelsonReportPage;
	public CATTSApprovalPage cATTSApprovalPage;
	public GTOPSSchedulePage gtOpsSchedulePage;

	public AccountingTab accountingTab;
	public ActionGTApprovedInvoicePage actionGTApprovedInvoicePage;
	public ActionGTInvoicePage actionGTInvoicePage;
	public FindGTInvoicePage findGTInvoicePage;
	public FindInvoicesPage findInvoicesPage;
	public GTUsageGroundTransportationPage gtUsageGroundTransportationPage;
	public GTUsagePage gtUsagePage;
	public ReconcilledInvoicesPage reconcilledInvoicesPage;
	public SupplierInvoicesPage supplierInvoicesPage;
	public ApprovedInvoicesPage approvedInvoicesPage;

	public ReportsTab reportsTab;
	public AccountingReportsPage accountingReportsPage;
	public CATTSReportPage cattsReportPage;
	public ConsolidateRoomSummaryReportPage consolidateRoomSummaryReportPage;
	public GLCodeReportPage glCodeReportPage;
	public GTConsolidatedInvoicePage gtConsolidatedInvoicePage;
	public GTOracleReportPage gtOracleReportPage;
	public GTPaymentFileReportsPage gtPaymentFileReportsPage;
	public PlanningReportsPage planningReportsPage;
	public GTUsageReportPage gtUsageReportPage;
	public TaxGLCodeReportPage taxGLCodeReportPage;
	public TaxExemptionReportPage taxExemptionReportPage;
	public NoShowReportPage noShowReportPage;
	public CrewIDIssueReportPage crewIDIssueReportPage;
	public RoomUsageExtractPage roomUsageExtractPage;

	public AdminTab adminTab;
	public AuditHistoryPage auditHistoryPage;
	public ViewResourceStatusPage viewResourceStatusPage;
	public CreateUserPage createUserPage;
	public FindUserPage findUserPage;
	public ManageDateConfigurationPage manageDateConfigurationPage;
	public ManageGroupsPage manageGroupsPage;
	public SystemAdminPage systemAdminPage;

	public MyAccountTab myAccountTab;
	public EditProfilePage editProfilePage;

	public ChangeTenantLink changeTenantLink;

	public HelperClass helper;
	public GenericClass genericClass;

	public Page_Login_Aces3Supplier aces3SupplierLoginPage;
	public Page_Home_Aces3Supplier aces3SupplierHomePage;
	public Page_SupplierSchedules_Aces3Supplier aces3SupplierSchedulesPage;
	public Page_Reservations_Aces3Supplier aces3SupplierReservationsPage;

	public Page_Login_ACES3ACES aces3acesLoginPage;
	public Page_Home_ACES3ACES aces3acesHomePage;
	public Page_Configuration_ACES3ACES aces3acesConfigurationPage;
	public Page_ManageEDrive_ACES3ACES aces3acesManageEdrivePage;
	public Page_EDriveDashboard_ACES3ACES aces3acesEDriveDashboardPage;
	public Page_SignInSheets_Aces3Supplier aces3SignInSheetsClientPage;
	public Page_UploadInvoice_Aces3Supplier aces3SupplierUploadInvoicePage;
	public Page_InvoiceDashboard_Aces3Supplier aces3SupplierInvoiceDashboardPage;

	public Page_CreateUser_Aces3Supplier aces3SupplierCreateUserPage;
	public Page_ManageUsers_Aces3Supplier aces3SupplierManageUsersPage;
	public Page_ManageRoles_Aces3Supplier aces3SupplierManageRolesPage;
	public Page_CreateRole_Aces3Supplier aces3SupplierCreateRolePage;
	public Page_EditUserAccount_Aces3Supplier aces3SupplierEditUserAccountPage;
	public Page_AccountConfirmation_Aces3Supplier aces3SupplierAccountConfirmationPage;
	public Page_AccountManagement_Aces3Supplier aces3SupplierAccountManagementPage;
	public Page_NewInvoices_Aces3Supplier aces3SuppliernewInvoicesPage;
	public Page_ChallengeInvoice_Aces3Supplier aces3SupplierChallegeInvoicePage;
	public Page_ReviewedInvoices_Aces3Supplier aces3SupplierReviewedInvoicesPage;
	public Page_TaxInvoice_Aces3Supplier aces3SupplierTaxInvoicePage;	
	public Page_Accounting_Aces3Client aces3ClientAccountingPage;
	public Page_PendingActionQueue_Aces3Supplier aces3SupplierAccountingPage;

	public Page_Reports_ACES3ACES aces3acesReportsPage;
	public Page_TaxExemptionReport_ACES3ACES aces3acesTaxExemptionReportPage;
	public Page_NoShowreport_ACES3ACES aces3acesNoShowReportPage;
	public Page_CrewIDIssuesReport_ACES3ACES aces3acesCrewIDIssuesPage;
	public Page_RecoverableTaxReport_ACES3ACES aces3acesRecoverableTaxReportPage;
	public Page_InvoiceStatusReport_ACES3ACES aces3acesInvoiceStatusReportPage;
	public Page_MasterOpsReport_ACES3ACES aces3acesMasterOpsReportPage;
	public Page_FindInvoice_Aces3Client aces3ClientFindInvoicePage;
	public Page_ManualInvoice_ACES3ACES aces3acesManualInvoicePage;
	public Page_Accounting_ACES3ACES aces3acesAccountingPage;
	public Page_GTInvoicing_CreateManaulInvoice aces2GTInvoicingCreateManualInvoicePage;
	public Page_TaxInvoice_Aces3Client aces3ClientTaxInvoicePage;

	public Page_Home_Aces3Client aces3ClientHomePage;
	public Page_GroundTransportation airlinesGroundTransportationPage;	
	public Page_AirlinesReport_ACES3ACES aces3AirlinesReportPage;

	public Page_AccountManagement_Aces3Client aces3ClientAccountManagementPage;	
	public Page_SignInSheets_ACES3ACES aces3SignInSheetsPage;
	public Page_AccurualSnapshot_ACES3ACES aces3acesAccurualSnapshotPage;

	public Page_EnterOnlineSignInSheets_Aces3Supplier aces3SupplierEnterOnlineSignInSheetsPage;
	public Page_CreateInvoice_Aces3Supplier aces3SupplierCreateInvoicePage;
	public Page_InvoiceComplianceReport_ACES3ACES aces3acesInvoiceComplianceReportPage;

	public Page_Admin_Aces3Client aces3ClientAdminReportsPage;

	public Page_AccountingFinancialReport_ACES3ACES aces3acesAccountingFinancialReportPage;

	public Page_ConsolidatedEInvoiceReport_ACES3ACES aces3acesConsolidateEInvoiceReportPage;
	public Page_CreateAllowanceInvoice_Aces3Supplier aces3SupplierCreateAllowanceInvoicePage;
	public Page_CreateViewAllowanceSIS_Aces3Supplier aces3SupplierCreateViewAllowanceSISPage;
	public Page_ViewAllowanceForecasts_Aces3Supplier aces3SupplierViewAllowanceForecastsPage;
	
	public Page_FindAllowanceInvoice_Aces3Supplier aces3SupplierFindAllowanceInvoicePage;
	public ViewSubmittedAllowanceInvoicesPage viewSubmittedAllowanceInvoicePage;
	public Page_SearchAdhocAllowanceRequest_Aces3Supplier aces3SupplierSearchAdhocAllowanceRequestPage;
	
	public Page_ManageUsers_Aces3Aces aces3acesManageUsersPage;
	public Page_CreateUser_Aces3Aces aces3acesCreateUser;
	public Page_EditUserAccount_Aces3Aces aces3acesEditUserAccountPage;
	
	public PgWrapper(EventFiringWebDriver driver) {
		pageLoginACESII = new Page_Login_ACESII(driver);
		pageHome = new Page_Home(driver);
		supplierProfileMenu = new SupplierProfileMenu(driver);
		pageAddNewAirlineSupplier = new Page_AddNewAirlineSupplier(driver);
		pageAirlineHotelSupplier = new Page_AirlineHotelSupplier(driver);
		pageAirlineGTSupplier = new Page_AirlineGTSupplier(driver);
		pageHotelSupplierContractDetails = new Page_HotelSupplier_ContractDetails(driver);
		pageFindExistingAirlineSupplier = new Page_FindExistingAirlineSupplier(driver);
		pageAddNewCommonSupplier = new Page_AddNewCommonSupplier(driver);
		pageFindCommonSupplier = new Page_FindCommonSupplier(driver);
		pageCommonHotelGeneralInfo = new Page_CommonHotelGeneralInfo(driver);
		pageCommonGTGeneralInfo = new Page_CommonGTGeneralInfo(driver);
		pageSortSuppliers = new Page_SortSuppliers(driver);
		pageAirportToAirportTransitTimes = new Page_AirportToAirportTransitTimes(driver);
		pageGateTimes = new Page_GateTimes(driver);
		pageManageVenues = new Page_ManageVenues(driver);

		opsDeskMenu = new OpsDeskMenu(driver);
		pageDashBoard = new Page_DashBoard(driver);
		pageFindTrip = new Page_FindTrip(driver);
		pagePendingConfirmations = new Page_PendingConfirmations(driver);
		pageHotelSchedules = new Page_HotelSchedules(driver);
		pageGTSchedules = new Page_GTSchedules(driver);
		pageFindGTSchedules = new Page_FindGTSchedules(driver);
		pageFindReservation = new Page_FindReservation(driver);
		pageAddHotelReservation = new Page_AddHotelReservation(driver);
		pageAddHotelReservationInformation = new Page_AddHotelReservationInformation(driver);
		pageGenerateCrewSignInSheet = new Page_GenerateCrewSignInSheet(driver);
		pageFindSheet = new Page_FindSheet(driver);
		pageIgnoreReservation = new Page_IgnoreReservation(driver);
		pageCancelReservation = new Page_CancelReservation(driver);
		pageTripAssignmentConfirmation = new Page_TripAssignmentConfirmation(driver);

		reportsMenu = new ReportsMenu(driver);
		pageReports = new Page_Reports(driver);
		pageHotelExport = new Page_HotelExport(driver);
		pageAgentReport = new Page_AgentReport(driver);
		pageAirlineReport = new Page_AirlineReport(driver);
		pageTripTrackingReport = new Page_TripTrackingReport(driver);

		adminMenu = new AdminMenu(driver);
		pageManageUsers = new Page_ManageUsers(driver);
		pageManageGroups = new Page_ManageGroups(driver);
		pageManageTenantFeatures = new Page_ManageTenantFeatures(driver);
		pagefaxStatus = new Page_FaxStatus(driver);
		pageGtEInvoiceConfiguration = new Page_GTEInvoiceConfiguration(driver);
		pageManageGroundTransportSchedule = new Page_ManageGroundTransportSchedule(driver);
		pageHotelAllowanceConfiguration = new Page_HotelAllowanceConfiguration(driver);
		pageMultiNightGrouping = new Page_MultiNightGrouping(driver);

		planningMenu = new PlanningMenu(driver);
		bulkAssignPage = new Page_BulkAssign(driver);
		errorsWarningsPage = new Page_ErrorsWarnings(driver);
		assignmentsPage = new Page_Assignments(driver);
		exportPairingsPage = new Page_ExportPairings(driver);
		migratePage = new Page_Migrate(driver);
		configurationPage = new Page_Configuration(driver);

		schedulesMenu = new SchedulesMenu(driver);
		createSchedulesPage = new Page_CreateSchedules(driver);
		viewSchedulesPage = new Page_ViewSchedules(driver);
		scheduleNotesPage = new Page_ScheduleNotes(driver);
		lockSchedulesPage = new Page_LockSchedules(driver);
		readyToExportPage = new Page_ReadyToExport(driver);

		airlinesLoginPage = new AirlinesLoginPage(driver);

		planningTab = new PlanningTab(driver);
		exportAssignedPairingsPage = new ExportAssignedPairingsPage(driver);
		exportHotelsPage = new ExportHotelsPage(driver);
		exportPairingPage = new ExportPairingsPage(driver);
		supplierSchedulesPage = new SupplierSchedulesPage(driver);
		uploadPairingsPage = new UploadPairingsPage(driver);
		uploadRoamingListPage = new UploadRoamingListPage(driver);

		operationsTab = new OperationsTab(driver);
		acesDirectFindReservationPage = new AcesDirectFindReservationPage(driver);
		acesDirectRequestLimoPage = new AcesDirectRequestLimoPage(driver);
		acesDirectRequestReservationPage = new AcesDirectRequestReservationPage(driver);
		actionStatusPage = new ActionStatusPage(driver);
		createAdhocAllowancePage = new CreateAdhocAllowancePage(driver);
		deadHeadsPage = new DeadHeadsPage(driver);
		deaReportPage = new DEAReportPage(driver);
		findPairingsPage = new FindPairingsPage(driver);
		findReservationBTPage = new FindReservationBTPage(driver);
		findReservationsPage = new FindReservationsPage(driver);
		findSheetPage = new FindSheetPage(driver);
		findOrEditRoomBlockRequestsPage = new FindOrEditRoomBlockRequestsPage(driver);
		generateSheetPage = new GenerateSheetPage(driver);
		hotelInfoPage = new HotelInfoPage(driver);
		paymentExtractReportPage = new PaymentExtractReportPage(driver);
		requestConferenceRoomPage = new RequestConferenceRoomPage(driver);
		requestLimoPage = new RequestLimoPage(driver);
		requestReservationPage = new RequestReservationPage(driver);
		requestRoomBlockPage = new RequestRoomBlockPage(driver);
		reservationPage = new ReservationPage(driver);
		roomUsagePage = new RoomUsagePage(driver);
		searchAdhocAllowancePage = new SearchAdhocAllowancePage(driver);
		viewForecastsPage = new ViewForecastsPage(driver);
		viewApprovedAllowanceInvoicePage = new ViewApprovedAllowanceInvoicePage(driver);
		viewAllowanceInvoicePage = new ViewAllowanceInvoicePage(driver);
		viewAllowanceTransactionsPage = new ViewAllowanceTransactionsPage(driver);
		vendorMismatchPage = new VendorMismatchPage(driver);
		configureSupplierFeaturesPage = new ConfigureSupplierFeaturesPage(driver);
		airNelsonReportPage = new AirNelsonReportPage(driver);
		cATTSApprovalPage = new CATTSApprovalPage(driver);
		gtOpsSchedulePage = new GTOPSSchedulePage(driver);

		accountingTab = new AccountingTab(driver);
		actionGTApprovedInvoicePage = new ActionGTApprovedInvoicePage(driver);
		actionGTInvoicePage = new ActionGTInvoicePage(driver);
		findGTInvoicePage = new FindGTInvoicePage(driver);
		findInvoicesPage = new FindInvoicesPage(driver);
		gtUsageGroundTransportationPage = new GTUsageGroundTransportationPage(driver);
		gtUsagePage = new GTUsagePage(driver);
		reconcilledInvoicesPage = new ReconcilledInvoicesPage(driver);
		supplierInvoicesPage = new SupplierInvoicesPage(driver);

		reportsTab = new ReportsTab(driver);
		accountingReportsPage = new AccountingReportsPage(driver);
		cattsReportPage = new CATTSReportPage(driver);
		consolidateRoomSummaryReportPage = new ConsolidateRoomSummaryReportPage(driver);
		glCodeReportPage = new GLCodeReportPage(driver);
		gtConsolidatedInvoicePage = new GTConsolidatedInvoicePage(driver);
		gtOracleReportPage = new GTOracleReportPage(driver);
		gtPaymentFileReportsPage = new GTPaymentFileReportsPage(driver);
		planningReportsPage = new PlanningReportsPage(driver);
		gtUsageReportPage = new GTUsageReportPage(driver);
		taxGLCodeReportPage = new TaxGLCodeReportPage(driver);
		approvedInvoicesPage = new ApprovedInvoicesPage(driver);
		taxExemptionReportPage = new TaxExemptionReportPage(driver);
		noShowReportPage = new NoShowReportPage(driver);
		crewIDIssueReportPage = new CrewIDIssueReportPage(driver);
		roomUsageExtractPage = new RoomUsageExtractPage(driver);

		adminTab = new AdminTab(driver);
		auditHistoryPage = new AuditHistoryPage(driver);
		createUserPage = new CreateUserPage(driver);
		findUserPage = new FindUserPage(driver);
		manageDateConfigurationPage = new ManageDateConfigurationPage(driver);
		manageGroupsPage = new ManageGroupsPage(driver);
		systemAdminPage = new SystemAdminPage(driver);
		viewResourceStatusPage = new ViewResourceStatusPage(driver);

		myAccountTab = new MyAccountTab(driver);
		editProfilePage = new EditProfilePage(driver);

		accountingMenu = new AccountingMenu(driver);
		pageSignInReport = new Page_SignInReport(driver);
		pageFindInvoice = new Page_FindInvoice(driver);
		pageManageOpenInvoice = new Page_ManageOpenInvoice(driver);
		pageCreateManualInvoice = new Page_CreateManualInvoice(driver);
		pageApproveManualInvoice = new Page_ApproveManualInvoice(driver);
		pageCreateProfarmaInvoices = new Page_CreateProfarmaInvoices(driver);
		pageCreateConsolidatedInvoices = new Page_CreateConsolidatedInvoices(driver);
		pageViewConsolidatedInvoices = new Page_ViewConsolidatedInvoice(driver);
		pageFindReconcileInvoie = new Page_FindReconcileInvoice(driver);
		pageCreateConsolidatedReconcileInvoice = new Page_CreateConsolidatedReconcileInvoice(driver);
		pageViewConsolidatedReconcileInvoice = new Page_ViewConsolidatedReconcileInvoice(driver);
		pageCreditCardReport = new Page_CreditCardReport(driver);
		pageGTInvoicingCreateInvoice = new Page_GtEInvoicing_CreateInvoice(driver);
		pageGTInvoicingFindInvoice = new Page_GtEInvoicing_FindInvoices(driver);
		pageGTInvoicingEdriveDashboard = new Page_GTInvoicing_EdriveGTDashboard(driver);

		changeTenantLink = new ChangeTenantLink(driver);
		helper = new HelperClass();
		genericClass = new GenericClass();

		aces3SupplierLoginPage = new Page_Login_Aces3Supplier(driver);
		aces3SupplierHomePage = new Page_Home_Aces3Supplier(driver);
		aces3SupplierSchedulesPage = new Page_SupplierSchedules_Aces3Supplier(driver);
		aces3SupplierReservationsPage = new Page_Reservations_Aces3Supplier(driver);
		aces3acesManageEdrivePage = new Page_ManageEDrive_ACES3ACES(driver);
		aces3SupplierReservationsPage = new Page_Reservations_Aces3Supplier(driver);
		aces3acesLoginPage = new Page_Login_ACES3ACES(driver);
		aces3acesHomePage = new Page_Home_ACES3ACES(driver);
		aces3acesConfigurationPage = new Page_Configuration_ACES3ACES(driver);
		aces3acesManageEdrivePage = new Page_ManageEDrive_ACES3ACES(driver);
		aces3acesEDriveDashboardPage = new Page_EDriveDashboard_ACES3ACES(driver);
		aces3SignInSheetsClientPage = new Page_SignInSheets_Aces3Supplier(driver);
		aces3SupplierCreateUserPage = new Page_CreateUser_Aces3Supplier(driver);
		aces3SupplierManageUsersPage = new Page_ManageUsers_Aces3Supplier(driver);
		aces3SupplierManageRolesPage = new Page_ManageRoles_Aces3Supplier(driver);
		aces3SupplierCreateRolePage = new Page_CreateRole_Aces3Supplier(driver);
		aces3SupplierEditUserAccountPage = new Page_EditUserAccount_Aces3Supplier(driver);
		aces3SupplierAccountConfirmationPage = new Page_AccountConfirmation_Aces3Supplier(driver);
		aces3SupplierAccountManagementPage = new Page_AccountManagement_Aces3Supplier(driver);
		aces3SuppliernewInvoicesPage = new Page_NewInvoices_Aces3Supplier(driver);
		aces3SupplierChallegeInvoicePage = new Page_ChallengeInvoice_Aces3Supplier(driver);
		aces3SupplierReviewedInvoicesPage = new Page_ReviewedInvoices_Aces3Supplier(driver);
		aces3acesManualInvoicePage = new Page_ManualInvoice_ACES3ACES(driver);
		aces3acesAccountingPage = new Page_Accounting_ACES3ACES(driver);
		aces3SupplierEnterOnlineSignInSheetsPage = new Page_EnterOnlineSignInSheets_Aces3Supplier(driver);
		aces3SupplierCreateInvoicePage = new Page_CreateInvoice_Aces3Supplier(driver);
		aces3SupplierTaxInvoicePage = new Page_TaxInvoice_Aces3Supplier(driver);
		aces3SupplierUploadInvoicePage = new Page_UploadInvoice_Aces3Supplier(driver);
		aces3acesReportsPage = new Page_Reports_ACES3ACES(driver);
		aces3acesTaxExemptionReportPage = new Page_TaxExemptionReport_ACES3ACES(driver);		
		aces3acesReportsPage = new Page_Reports_ACES3ACES(driver);
		aces3acesTaxExemptionReportPage = new Page_TaxExemptionReport_ACES3ACES(driver);		
		aces3acesNoShowReportPage = new Page_NoShowreport_ACES3ACES(driver);
		aces3acesAccountingPage = new Page_Accounting_ACES3ACES(driver);
		aces3acesCrewIDIssuesPage = new Page_CrewIDIssuesReport_ACES3ACES(driver);
		aces3acesRecoverableTaxReportPage = new Page_RecoverableTaxReport_ACES3ACES(driver);
		aces3acesInvoiceStatusReportPage = new Page_InvoiceStatusReport_ACES3ACES(driver);
		aces3acesMasterOpsReportPage = new Page_MasterOpsReport_ACES3ACES(driver);
		aces3SupplierUploadInvoicePage = new Page_UploadInvoice_Aces3Supplier(driver);
		aces3SupplierInvoiceDashboardPage = new Page_InvoiceDashboard_Aces3Supplier(driver);
		aces3ClientFindInvoicePage = new Page_FindInvoice_Aces3Client(driver);
		aces3SupplierUploadInvoicePage = new Page_UploadInvoice_Aces3Supplier(driver);
		aces3acesManualInvoicePage = new Page_ManualInvoice_ACES3ACES(driver);
		aces3acesAccountingPage = new Page_Accounting_ACES3ACES(driver);
		aces3acesCrewIDIssuesPage = new Page_CrewIDIssuesReport_ACES3ACES(driver);
		aces3acesRecoverableTaxReportPage = new Page_RecoverableTaxReport_ACES3ACES(driver);
		aces3acesInvoiceStatusReportPage = new Page_InvoiceStatusReport_ACES3ACES(driver);
		aces3acesMasterOpsReportPage = new Page_MasterOpsReport_ACES3ACES(driver);
		aces3SupplierUploadInvoicePage = new Page_UploadInvoice_Aces3Supplier(driver);
		aces3SupplierInvoiceDashboardPage = new Page_InvoiceDashboard_Aces3Supplier(driver);
	//	aces3ClientFindInvoicePage = new Page_FindInvoice_Aces3Client(driver);
		aces3SupplierUploadInvoicePage = new Page_UploadInvoice_Aces3Supplier(driver);
		aces3ClientTaxInvoicePage = new Page_TaxInvoice_Aces3Client(driver);
		aces3SupplierCreateInvoicePage = new Page_CreateInvoice_Aces3Supplier(driver);
		aces3SupplierTaxInvoicePage = new Page_TaxInvoice_Aces3Supplier(driver);
		aces3acesInvoiceComplianceReportPage = new Page_InvoiceComplianceReport_ACES3ACES(driver);
		aces3SupplierEnterOnlineSignInSheetsPage = new Page_EnterOnlineSignInSheets_Aces3Supplier(driver);
		airlinesGroundTransportationPage = new Page_GroundTransportation(driver);
		aces3SignInSheetsPage = new Page_SignInSheets_ACES3ACES(driver);
		aces3AirlinesReportPage = new Page_AirlinesReport_ACES3ACES(driver);
		aces3ClientAdminReportsPage = new Page_Admin_Aces3Client(driver);		
		aces3acesAccountingFinancialReportPage = new Page_AccountingFinancialReport_ACES3ACES(driver);
		aces3acesConsolidateEInvoiceReportPage = new Page_ConsolidatedEInvoiceReport_ACES3ACES(driver);
		aces3acesAccurualSnapshotPage = new Page_AccurualSnapshot_ACES3ACES(driver);		
		aces3ClientAccountManagementPage = new Page_AccountManagement_Aces3Client(driver);	
		aces3SupplierCreateAllowanceInvoicePage = new Page_CreateAllowanceInvoice_Aces3Supplier(driver);
		aces3SupplierCreateViewAllowanceSISPage = new Page_CreateViewAllowanceSIS_Aces3Supplier(driver);
		aces3SupplierViewAllowanceForecastsPage = new Page_ViewAllowanceForecasts_Aces3Supplier(driver);
		aces3SupplierViewAllowanceForecastsPage = new Page_ViewAllowanceForecasts_Aces3Supplier(driver);
		aces3acesAccurualSnapshotPage = new Page_AccurualSnapshot_ACES3ACES(driver);		

		aces3SupplierSearchAdhocAllowanceRequestPage = new Page_SearchAdhocAllowanceRequest_Aces3Supplier(driver);
		aces3SupplierFindAllowanceInvoicePage = new Page_FindAllowanceInvoice_Aces3Supplier(driver);
		viewSubmittedAllowanceInvoicePage = new ViewSubmittedAllowanceInvoicesPage(driver);
		aces3SupplierSearchAdhocAllowanceRequestPage = new Page_SearchAdhocAllowanceRequest_Aces3Supplier(driver);
		aces3ClientAccountingPage = new Page_Accounting_Aces3Client(driver);
		aces3ClientHomePage = new Page_Home_Aces3Client(driver);
		aces3ClientAccountingPage = new Page_Accounting_Aces3Client(driver);
		pageFindInvoice = new Page_FindInvoice (driver);
		
		
		aces3acesCreateUser = new Page_CreateUser_Aces3Aces(driver);
		aces3acesManageUsersPage = new Page_ManageUsers_Aces3Aces(driver);
		aces3acesEditUserAccountPage = new Page_EditUserAccount_Aces3Aces(driver);
		
	}	

}
